csk/urls.py
from django.urls import path
from csk.views import*
app_name='csk'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from csk.views import*
from rcb.views import *
from india.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
    path('sewhag/',sewhag,name='sewhag'),
    path('akt/',akt,name='akt'),
    path('bhavya/',bhavya,name='bhavya'),
    path('sinchana/',sinchana,name='sinchana'),
]

rcb/urls.py
from django.urls import path
from rcb.views import*
app_name='rcb'

urlpatterns=[
    path('virat/',virat,name='virat'),
]

csk/models.py
from django.db import models

# Create your models here.

india/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

def bhavya(request):
    return HttpResponse('<h1> hellooo bhavyaa </h1>')

india/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def sewhag(request):
    return render(request,'sewhag.html')

def akt(request):
    return HttpResponse('<h1> This String response')

rcb/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def virat(request):
    return render(request,'virat.html')

def sinchana(request):
    return HttpResponse('<h1> hellloooo sinchana</h1>')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is dhoni page</h1>
        <h1>Thank You</h1>
        <h2><a href="{% url 'rcb:virat' %}">go to virat page</a></h2>
        <h2><a href="{% url 'sewhag' %}">go to sewhag page</a></h2>
        <h2><a href="{% url 'akt' %}">go to akt page</a></h2>
        <h2><a href="{% url 'bhavya' %}">go to bhavya page</a></h2>
        <h2><a href="{% url 'sinchana' %}">go to sinchana page</a></h2>
        

    </center>
</body>
</html>

templates/sewhag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is sewhag page</h1>
        <h2><a href="{% url 'csk:dhoni' %}">go to dhoni page</a></h2>
        <h2><a href="{% url 'rcb:virat' %}">go to virat page</a></h2>
        <h2><a href="{% url 'akt' %}">go to akt page</a></h2>
        <h2><a href="{% url 'bhavya' %}">go to bhavya page</a></h2>
        <h2><a href="{% url 'sinchana' %}">go to sinchana page</a></h2>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is virat page</h1>
        <h1>congratulations</h1>
        <h2><a href="{% url 'csk:dhoni' %}">go to dhoni page</a></h2>
        <h2><a href="{% url 'sewhag' %}">go to sewhag page</a></h2>
        <h2><a href="{% url 'akt' %}">go to akt page</a></h2>
        <h2><a href="{% url 'bhavya' %}">go to bhavya page</a></h2>
        <h2><a href="{% url 'sinchana' %}">go to sinchana page</a></h2>
    </center>
    
</body>
</html>